---
- name: Write nodeos config
  template:
    src: config.ini.j2
    dest: "{{ host_data_dir }}/config.ini"

- name: Create nodeos container
  docker_container:
    restart: yes
    state: present
    image: "{{ docker_hub_image }}:{{ image_tag }}"
    name: nodeos
    command: /opt/eosio/bin/nodeosd.sh
    volumes:
      - "{{ host_data_dir }}:{{ eosio_container_data_dir }}"
    published_ports:
      - "{{ container_http_port }}:{{ container_http_port }}"
      - "{{ container_p2p_port }}:{{ container_p2p_port }}"
