---
- name: Install aptitude
  raw: apt-get -y install aptitude

- name: Add apt key for Docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker apt repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable

- name: Update and upgrade packages
  apt:
    upgrade=yes
    update_cache=yes

- name: Install system dependencies
  action: apt name={{ item }} state=present update_cache=yes
  with_items:
    - ntp
    - python3
    - python3-pip
    - python3-jinja2
    - python3-dev
    - docker-ce
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: Symlink python3 to python
  file:
    src: /usr/bin/python3
    dest: /usr/bin/python
    state: link

- name: Upgrade pip
  pip:
    name: pip
    extra_args: -U
    executable: pip3

- name: Install docker-py
  pip:
    name: docker
    executable: pip3

- name: Install docker-compose
  pip:
    name: docker-compose
    executable: pip3

- user:
    name: '{{ deploy_user }}'

- name: Create /data directory
  file: 
    path: /data
    state: directory

